GET http://localhost:3001/movies/
###

POST http://localhost:3001/movies/
Content-Type: application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###
GET http://localhost:3001/movies/47/
###

PUT http://localhost:3001/movies/46/
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###

DELETE http://localhost:3001/movies/46/
###

GET http://localhost:3001/directors/
###

GET http://localhost:3001/directors/10/movies/
###